### ISSUE TITLE
needs a collection of links to available extensions

### ISSUE THREAD

**Issue by nosarious** [OpenframeProject/Openframe-Extension#1]
I only found out about the openframeworks extension from your twitter feed. 
I tried to remedy it with a text file in the fork I made for this page (assuming this would have been the first place I would have looked) and included the extensions I could find (openframeworks, processing, tanagram, Ascii images)

I'm sure there are other ones I have not found yet. Is there a collection of links to available extensions which I have perhaps missed?

**Comment by jmwohl** [comment]
We should document a list somewhere, but for now this is probably the best way to see published extensions:

https://www.npmjs.com/search?q=openframe-extension
